server:
  port: 8082
  error:
    include-message: always

external:
  resource-service:
    base-url: "http://localhost:8081/"

spring:
  # Database Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3308/posts
    username: root
    password: ${PERSONAL_PROJECT_LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info