server:
  port: 8083

spring:
  # Database Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:shardingsphere:classpath:sharding.yml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver

logging:
  level:
    root: info